{
 "title": "GitHubDashboard",
 "time": { "from": "2020-07-12T01:56:03.407Z", "to": "2020-07-12T13:56:03.407Z" },
 "panels": [
  {
   "title": "Pull Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "10 Newest open unmerged Pull Requests",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "target": "db.github-issues.aggregate( [\n    {\"$match\":{\"$and\":[{\"type\":\"PULL_REQUESTS\"},{\"data.merged_at\":null},{\"data.state\": {\"$not\" : {\"$regex\":\"/closed$/\"}}}]}},\n    {\"$addFields\": {\"title\":\"$data.title\",\"created\":{\"$toDate\":\"$createdAt\"}}},\n    {\"$project\":{\"_id\":0,\"id\":0,\"type\":0,\"data\":0,\"createdAt\":0}},\n    { \"$sort\":{\"createdAt\":-1}},\n   { \"$limit\": 10 }\n] )",
     "type": "table"
    }
   ]
  },
  { "title": "Issues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "uncommented issues",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "db.github-issues.aggregate(\n    [\n        { \n            \"$match\": \n            { \n                \"$and\":[{\"type\": \"ISSUES\"},{\"data.comments\": { \"$lt\": 1} }]\n            } \n        },\n        {\n          \"$count\": \"uncommented_issues\"\n    }\n    ]\n)",
     "type": "table"
    }
   ]
  },
  { "title": "Commits", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Top 10 Commiter",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "target": "db.github-issues.aggregate( [\n    {\"$match\":{\"type\":\"COMMITS\"}},\n  {\n    \"$group\": {\n       \"_id\": \"$data.author.login\",\n       \"count\": { \"$sum\": 1 }\n    }\n  },\n  {\"$sort\":{\"count\":-1}},\n  {\"$limit\":10}\n] )",
     "type": "table"
    }
   ]
  }
 ]
}